### ISSUE TITLE
 `afpd` daemon segfaults inside the `afp_exchangefiles` function

### ISSUE THREAD

**Issue by ondrejholy** [Netatalk/netatalk#1762]
**Describe the bug**
The `afpd` daemon segfaults inside the `afp_exchangefiles` function when interacting with gvfs client.

**To Reproduce**
```
$ gio mount afp://rpi.local/shared
$ echo "foo" | gio save afp://rpi.local/shared/bar # this creates new file
$ echo "foo" | gio save afp://rpi.local/shared/bar # this replaces the existing file using exchange
gio: afp://rpi.local/shared/bar: Error in stream protocol: End of stream
```

**Expected behavior**
It should not crash...

**Environment**
 - Server OS: Raspbian 12
 - Client OS: Fedora 41
 - Netatalk Version: 3.1.13~ds-2

**Logs**
Attach syslogs from the malfunctioning process, `maxdebug` log level
```
Nov 18 11:02:03 rpi afpd[1950]: <== Start AFP command: AFP_EXCHANGEFILE
Nov 18 11:02:03 rpi afpd[1950]: dirlookup(did: 2): START
Nov 18 11:02:03 rpi afpd[1950]: dirlookup(did: 2): RESULT: pdid: 1, path: "/home/oholy/shared"
Nov 18 11:02:03 rpi afpd[1950]: cname('/home/oholy/shared'): {start}
Nov 18 11:02:03 rpi afpd[1950]: movecwd: from: curdir:"/home/oholy/shared", cwd:"/home/oholy/shared"
Nov 18 11:02:03 rpi afpd[1950]: movecwd(to: did: 2, "/home/oholy/shared")
Nov 18 11:02:03 rpi afpd[1950]: cname_mtouname('bar',did:2) {demangled:'bar', fileid:0}
Nov 18 11:02:03 rpi afpd[1950]: came('/home/oholy/shared'): {node: 'bar}
Nov 18 11:02:03 rpi afpd[1950]: came('/home/oholy/shared'): {file: 'bar'}
Nov 18 11:02:03 rpi afpd[1950]: cname('/home/oholy/shared') {end: curdir:'/home/oholy/shared', path:'bar'}
Nov 18 11:02:03 rpi afpd[1950]: absupath: /home/oholy/shared/bar
Nov 18 11:02:03 rpi afpd[1950]: acltoownermode("/home/oholy/shared/bar", 0x86)
Nov 18 11:02:03 rpi afpd[1950]: ACL_GROUP_OBJ: 1000
Nov 18 11:02:03 rpi afpd[1950]: resulting user maccess: 0x86 group maccess: 0x06
Nov 18 11:02:03 rpi afpd[1950]: file_access("bar"): mapped user mode: 0x86
Nov 18 11:02:03 rpi afpd[1950]: dirlookup(did: 2): START
Nov 18 11:02:03 rpi afpd[1950]: dirlookup(did: 2): RESULT: pdid: 1, path: "/home/oholy/shared"
Nov 18 11:02:03 rpi afpd[1950]: cname('/home/oholy/shared'): {start}
Nov 18 11:02:03 rpi afpd[1950]: movecwd: from: curdir:"/home/oholy/shared", cwd:"/home/oholy/shared"
Nov 18 11:02:03 rpi afpd[1950]: movecwd(to: did: 2, "/home/oholy/shared")
Nov 18 11:02:03 rpi afpd[1950]: cname_mtouname('~gvf6x4v.tmp',did:2) {demangled:'~gvf6x4v.tmp', fileid:0}
Nov 18 11:02:03 rpi afpd[1950]: came('/home/oholy/shared'): {node: '~gvf6x4v.tmp}
Nov 18 11:02:03 rpi afpd[1950]: came('/home/oholy/shared'): {file: '~gvf6x4v.tmp'}
Nov 18 11:02:03 rpi afpd[1950]: cname('/home/oholy/shared') {end: curdir:'/home/oholy/shared', path:'~gvf6x4v.tmp'}
Nov 18 11:02:03 rpi afpd[1950]: acltoownermode("/home/oholy/shared/~gvf6x4v.tmp", 0x86)
Nov 18 11:02:03 rpi afpd[1950]: ACL_GROUP_OBJ: 1000
Nov 18 11:02:03 rpi afpd[1950]: resulting user maccess: 0x86 group maccess: 0x06
Nov 18 11:02:03 rpi afpd[1950]: file_access("~gvf6x4v.tmp"): mapped user mode: 0x86
Nov 18 11:02:03 rpi afpd[1950]: renamefile: src[-1, "/home/oholy/shared/bar"] -> dst[".AppleTempZm6UAm"]
Nov 18 11:02:03 rpi afpd[1950]: renamefile: src[-1, "~gvf6x4v.tmp"] -> dst["/home/oholy/shared/bar"]
Nov 18 11:02:03 rpi afpd[1950]: renamefile: src[-1, ".AppleTempZm6UAm"] -> dst["~gvf6x4v.tmp"]
Nov 18 11:02:03 rpi afpd[1937]: main: IPC request from child[1950]
Nov 18 11:02:03 rpi afpd[1937]: child[1950]: killed by signal 6
```

**Additional context**
If it is a crash, please attach a [stacktrace](https://github.com/Netatalk/netatalk/wiki/Using-GDB-to-Analyze-a-Crash).
```
Program received signal SIGSEGV, Segmentation fault.
0x76fa2084 in memcpy () from /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so
(gdb) bt
#0  0x76fa2084 in memcpy () from /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so
#1  0x00000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

See the `g_vfs_afp_volume_exchange_files` implementation:
https://gitlab.gnome.org/GNOME/gvfs/-/blob/5930dd09/daemon/gvfsafpvolume.c#L2439-2477

**Comment by NJRoadfan** [comment]
Please post your `afp.conf`.

In addition, is it possible to test with Netatalk 3.2 or newer? The `ad_copy_header()` function, which is called by `afp_exchangefiles` saw some fixes since 3.1.13.

**Comment by NJRoadfan** [comment]
Initial testing with Netatalk 4.0.5 shows this as working and fixed in the latest release. Client used is the stock `gvfs `and `gvfs-backends` (1.50.3-1) package included with Debian Bookworm. The Netatalk 3.1.13~ds-2 package doesn't appear to have this PR applied: https://github.com/Netatalk/netatalk/commit/7dbde0ce704be7fbdb23e893e05cedced337350d

**Comment by ondrejholy** [comment]
> Please post your `afp.conf`.
```
[shared]
 path = /home/oholy/shared
```
> In addition, is it possible to test with Netatalk 3.2 or newer?

Debian Bookworm doesn't have a newer package available and that device doesn't have enough disk space for compilation. But I have just tried on another device where is `netatalk-3.1.18-1.fc39.x86_64` and it works fine. So if this is not ARM-specific bug, it looks to be solved... 

Thanks!

**Comment by rdmark** [comment]
Thanks for the follow-up! I'm relieved that it wasn't a new bug.

And good news: netatalk has been accepted back into Debian. Version 4.0 is expected to be distributed with Debian Trixie when it drops next year.
